# Generated by Django 5.1.6 on 2025-02-13 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ParticipantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.image')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.participant')),
            ],
        ),
    ]
