# Generated by Django 4.2.9 on 2025-02-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_participant_current_index_participantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_colorblind',
            field=models.BooleanField(default=False),
        ),
    ]
